<div class="newblog">
        <ul>
          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          <div class="autor"><span>作者：[field:writer/]</span><span>分类：[<a href="[field:typeurl/]">[field:typename/]</a>]</span><span>浏览（<a href="/">[field:click/]</a>）</span></div>
          <p>[field:description/]<a href="[field:arcurl/]" target="_blank" class="readmore">全文</a></p>
        </ul>
        <figure><img src="[field:litpic/]" ></figure>
        <div class="dateview">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</div>
      </div>