<div class="newblog">
        <ul>
          <h3><a href="/">再看4年前某婚恋网站我的十条征婚条件</a></h3>
          <div class="autor"><span>作者：杨青</span><span>分类：[<a href="/">日记</a>]</span><span>浏览（<a href="/">459</a>）</span><span>评论（<a href="/">30</a>）</span></div>
          <p>意外的是这个当地的婚恋网站到目前还存在，更意外的是，我的个人帐号还保存在他们网站上。好奇心迫使我打开个人资料看看到底当年写了什么样的征婚条件。原来这些年这些标准一直都没有变过，因为习惯，所以喜欢！ <a href="/" target="_blank" class="readmore">全文</a></p>
        </ul>
        <figure><img src="{dede:global.cfg_templets_skin/}/images/005.jpg" ></figure>
        <div class="dateview">2014-04-08</div>
      </div>