<div class="blogs">
        <h3><a href="/">[field:title/]</a></h3>
        <figure><img src="[field:litpic/]" ></figure>
        <ul>
          <p>[field:description/]</p>
          <a href="[field:arcurl/]" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
        </ul>
        <p class="autor"><span>作者：[field:writer/]</span><span>分类：【<a href="[field:typeurl/]">[field:typename/]</a>】</span><span>浏览（<a href="/">[field:click/]</a>）</span></p>
        <div class="dateview">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</div>
      </div>