<?php
$z[0]=Array("global","",64,90);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",131,153);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",193,218);
$z[2][4]['name']="description";
$z[3]=Array("global","",236,268);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",314,346);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",393,425);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",583,615);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("channel","\r\n        <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n      ",991,1106);
$z[7][4]['type']="top";
$z[7][4]['row']="10";
$z[8]=Array("arclist","\r\n      <div class=\"blogs\">\r\n        <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n        <figure><img src=\"[field:litpic/]\" ></figure>\r\n        <ul>\r\n          <p>[field:description/]</p>\r\n          <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"readmore\">阅读全文&gt;&gt;</a>\r\n        </ul>\r\n        <p class=\"autor\"><span>作者：[field:writer/]</span><span>分类：【<a href=\"[field:typeurl/]\">[field:typename/]</a>】</span><span>浏览（<a href=\"/\">[field:click/]</a>）</span></p>\r\n        <div class=\"dateview\">[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]</div>\r\n      </div>\r\n      ",1495,2163);
$z[8][4]['flag']="c";
$z[8][4]['row']="10";
$z[9]=Array("global","",4975,5007);
$z[9][4]['name']="cfg_templets_skin";

?>